version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
  post_build:
    commands:
    - echo Build completed on `date`
    - cd app1
    - mvn package
    - mv target/hello-1.0.war hello-1.0.war
    - cd ..
    - cp app1/target/hello-1.0.war .
    - cd app2
    - mvn package
    - mv target/hello-2.0.war hello-2.0.war
    - cd ..
    - cp app2/target/hello-2.0.war .
#    - boxfuse run target/hello-1.0.war
artifacts:
  files:
  - hello-1.0.war
  - hello-2.0.war
  - .ebextensions/**/*
